version: '3.7'

services:
  elk:
    image: elasticsearch:7.14.2
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - kibana_elastic
    environment:
      - discovery.type=single-node
    restart: always

  kibana:
    image: kibana:7.14.2
    ports:
      - "5601:5601"
    networks:
      - kibana_elastic
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    restart: always

networks:
  kibana_elastic:
    driver: bridge
